### ISSUE TITLE
Dispence one-hot-vectors

### ISSUE THREAD

**Issue by Zepp3** [UBCDingXin/improved_CcGAN#3]
Hi!

I still don't quite understand how it is possible to dispense on transforming y (or the condition) into one-hot-vectors, as the conditions still go through some layers as a scalar after being incorporated to D or G.

Kind regards!

**Comment by UBCDingXin** [comment]
It is usually impossible to transform a scalar continuous condition y into a one-hot vector because there are infinite distinct values that y can take. Please check Section 2.2  of our paper at https://arxiv.org/pdf/2011.07466.pdf, where two label input mechanisms are provided. In the improved label input mechanism, an embedding network is learned to map a scalar continuous y into a high dimensional space and this high dimensional representation of y is fed into D and G.

**Comment by Zepp3** [comment]
Thanks! So I can assume that the high dimensional representation does not damage the relationship of the labels. 
Do you think that in general CcGAN is applicable to synthesize tabular data, not only image generation?

**Comment by UBCDingXin** [comment]
@Zepp3 

Please note that high dimensional representation is only used to input regression labels into D and G but the construction of a hard/soft vicinity for y is conducted in the original scale of y. 

If tabular data does not have discrete variables, CcGAN may apply.

**Comment by Zepp3** [comment]
@UBCDingXin 

Why wouldn't discrete variables in the data be suitable, as long as the labels are continuous?

**Comment by UBCDingXin** [comment]
@Zepp3 

CcGAN assumes the conditional image distribution is continuous.

**Comment by Zepp3** [comment]
Thanks!
